<?php namespace App\Http\Controllers\Buildings;
use Processing\Form\Form;

class BuildingsForm extends \Processing\Form\Form
{

    /**
     * @return PersoaneFiziceForm, obiect cu toate textbox-urile, cu blade-ul formularului, modelul, buttons (adauga, salveaza, sterge)
     */
    public static function make()
    {
        return self::$instance = new BuildingsForm();
    }

    protected function setView()
    {
        $this->view('buildings.form');
    }

    protected function setModel()
    {
        $this->model('App|Models|Build');
    }

    protected function addControls()
    {
        $this
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('name')
                    ->caption('Nume Cladire')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('name')
                    ->controltype('textbox')
                    ->maxlength(255)
            )

            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('address')
                    ->caption('Adresa')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('address')
                    ->controltype('textbox')
                    ->maxlength(255)

                    
            )

             ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('locality')
                    ->caption('Localitatea')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('locality')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
              ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('county')
                    ->caption('Judetul')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('county')
                    ->controltype('textbox')
                    ->maxlength(255)
            )

             ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('energy_responsable')
                    ->caption('Responsabil Energetic')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('energy_responsable')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
              ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('owner')
                    ->caption('Proprietar')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('owner')
                    ->controltype('textbox')
                    ->maxlength(255)
            )

             ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('destination')
                    ->caption('Destinatia Principala')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('destination')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
              ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('type_building')
                    ->caption('Tipul Cladirii')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('type_building')
                    ->controltype('textbox')
                    ->maxlength(255)
            )

             ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('year')
                    ->caption('Anul Constructiei')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('year')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
              ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('designer')
                    ->caption('Proiectant')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('designer')
                    ->controltype('textbox')
                    ->maxlength(255)
            )

             ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('builder')
                    ->caption('Constructor')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('builder')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
              ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('height')
                    ->caption('Regimul de Inaltime')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('height')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
             ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('structure_construct')
                    ->caption('Structura Constructiva')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('structure_construct')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('particularities')
                    ->caption('Particularitati')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('particularities')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
//anvelopa-------------------------------------------------------------------------
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('total_unfolded_area')
                    ->caption('Suprafata Totala Desfasurata Mp')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('total_unfolded_area')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('heated_surface')
                    ->caption('Suprafata Desfasurate Incalzita Mp')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('heated_surface')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('built_surface_ground')
                    ->caption('Suprafata Construita La Sol Mp')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('built_surface_ground')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('window_surface')
                    ->caption('Suprafata Totala Ferestre Exterioare Mp')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('window_surface')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('door_surface')
                    ->caption('Suprafata Usilor Exterioare Mp')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('door_surface')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('building_volume')
                    ->caption('Volum Total Cladire Mc')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('building_volume')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('heated_volume')
                    ->caption('Volum Incalzit Cladire Mc')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('heated_volume')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('average_height')
                    ->caption('Inaltime Medie M')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('average_height')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('exterior_walls')
                    ->caption('Pereti Exteriori')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('exterior_walls')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('thickness_extr_walls')
                    ->caption('Grosime Pereti Exteriori Mm')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('thickness_extr_walls')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('insulation_extr_walls')
                    ->caption('Izolatie Pereti Exteriori Mn')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('insulation_extr_walls')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('exterior_joiner_wood')
                    ->caption('Tamplarie Exterioara Termoizolanta Din Lemn Mp')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('exterior_joiner_wood')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('exterior_joiner_pvc')
                    ->caption('Tamplarie Exterioara Termoizolanta Din Pvc Mp')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('exterior_joiner_pvc')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('exterior_joiner_aluminium')
                    ->caption('Tamplarie Exterioara Termoizolanta Din Al Mp')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('exterior_joiner_aluminium')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('exterior_joiner_simple_wood')
                    ->caption('Tamplarie Exterioara Termoizolanta Simpla Din Lemn Mp')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('exterior_joiner_simple_wood')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('exterior_joiner_simple_metal')
                    ->caption('Tamplarie Exterioara Termoizolanta Simpla Metalica Mp')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('exterior_joiner_simple_metal')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('exterior_joiner_double')
                    ->caption('Tamplarie Exterioara Termoizolanta Dubla Cuplata Din Lemn Mp')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('exterior_joiner_double')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('terrace_state')
                    ->caption('Stare Acoperis Tip Terasa')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('terrace_state')
                    ->controltype('textbox')
                    ->maxlength(255)
            ) 
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox-addon')
                    ->name('last_repair')
                    ->caption('Ultima Reparatie Terasa')
                    ->class('form-control  data-source datepicker')
                    //->placeholder('Nume')
                    ->controlsource('last_repair')
                    ->controltype('textbox')
                    ->addon(['before' => '<i class="fa fa-calendar"></i>', 'after' => NULL])
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('roof_condition')
                    ->caption('Stare Acoperisului Peste Pod')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('roof_condition')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('roof_insulation')
                    ->caption('Izolatie Acoperis Mm')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('roof_insulation')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('plates_under_bridge')
                    ->caption('Planseu Sub Pod')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('plates_under_bridge')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('plates_insulation')
                    ->caption('Izolatie Planseu Mm')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('plates_insulation')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('plate_over_basement')
                    ->caption('Placa Peste Subsol Sol')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('plate_over_basement')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('plate_over_basement_insulation')
                    ->caption('Izolatie Placa Peste Subsol Sol Mm')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('plate_over_basement_insulation')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
//incalzire------------------------------------------------------------------------
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('energy_source')
                    ->caption('Sursa De Energie')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('energy_source')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('fuel_source')
                    ->caption('Sursa Proprie De Energie')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('fuel_source')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('description_source')
                    ->caption('Descriere Sursa De Incalzire')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('description_source')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('ctp_power')
                    ->caption('Ctp Putere Termica Instalata')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('ctp_power')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox-addon')
                    ->name('date_installation')
                    ->caption('Ctp Data Instalarii')
                    ->class('form-control  data-source datepicker')
                    //->placeholder('Nume')
                    ->controlsource('date_installation')
                    ->controltype('textbox')
                    ->addon(['before' => '<i class="fa fa-calendar"></i>', 'after' => NULL])
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('ctp_adjustment_system')
                    ->caption('Ctp Sistem Reglare Automatizare')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('ctp_adjustment_system')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('type_system')
                    ->caption('Tipul Sistemului De Incalzire')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('type_system')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('description_heating_system')
                    ->caption('Descriere Tip De Incalzire')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('description_heating_system')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('hydraulic_adjustment')
                    ->caption('Reglaj Corpuri Statice Termic Higraulic')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('hydraulic_adjustment')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('description_hydraulic_adjs')
                    ->caption('Descriere Reglaj Termic Higraulic')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('description_hydraulic_adjs')
                    ->controltype('textbox')
                    ->maxlength(255)
            ) 
//apa calda ----------------------------------------------------------------------
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('energy_source_')
                    ->caption('Sursa De Energie2')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('energy_source_')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('fuel_source_')
                    ->caption('Sursa Proprie De Energie2')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('fuel_source_')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('description_source_')
                    ->caption('Descriere Sursa De Apa Calda')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('description_source_')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('sp_power')
                    ->caption('Sp Putere Termica Nominala')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('sp_power')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox-addon')
                    ->name('date_installation_')
                    ->caption('Sp Data Instalarii')
                    ->class('form-control  data-source datepicker')
                    //->placeholder('Nume')
                    ->controlsource('date_installation_')
                    ->controltype('textbox')
                    ->addon(['before' => '<i class="fa fa-calendar"></i>', 'after' => NULL])
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('type_system_')
                    ->caption('Tipul Sistemului')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('type_system_')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('description_type_system')
                    ->caption('Descriere Tip Sistem')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('description_type_system')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('head_of_circulation')
                    ->caption('Conducta De Recirculare AA CC')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('head_of_circulation')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('program_delivery')
                    ->caption('Program Livrare Apa Clda Ore/Zi')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('program_delivery')
                    ->controltype('textbox')
                    ->maxlength(255)
            )
            ->addControl(
                \Easy\Form\Textbox::make('~layouts.form.controls.textboxes.textbox')
                    ->name('program_end_week')
                    ->caption('Program Sfarsit De Saptamina Ore/Zi')
                    ->class('form-control  data-source')
                    //->placeholder('Nume')
                    ->controlsource('program_end_week')
                    ->controltype('textbox')
                    ->maxlength(255)
            ) 
        ;      

    }
}